### ISSUE TITLE
Missing submodule

### ISSUE THREAD

**Issue by BugUser0815** [malsami/client-tools#13]
File .gitmodules branch "working" does not contain information for "operating-system".
Merge failed?

**Comment by privatereese** [comment]
Is this still an issue, branch "working" does not exist any more. Might have been fixed by 32d9de24ee880e9e1261f38ccc01db38802beb66

**Comment by RobertHa** [comment]
https://github.com/malsami/client-tools/blob/master/.gitmodules does not link to 'working' branch anymore and the 'datageneration' branch is working
