### ISSUE TITLE
double assignment of ip address

### ISSUE THREAD

**Issue by RobertHa** [malsami/client-tools#4]
In the [dhcpd.conf](https://github.com/malsami/client-tools/blob/working/dhcpd.conf) the subnet starts at 10.200.45.0,  the br0 gets assigned the ip 10.200.45.10 but the qemu instances receive the IPs from 10.200.45.1 to .42 so machine 10 is assigned to the same address as the br0.

**Comment by privatereese** [comment]
PR #5  is fixing this.
