### ISSUE TITLE
submodule links

### ISSUE THREAD

**Issue by RobertHa** [malsami/client-tools#7]
the submodule links still point to old versions, this should be updated

**Comment by privatereese** [comment]
To which commit should they point?

**Comment by RobertHa** [comment]
The master should always point to the latest other masters.

**Comment by privatereese** [comment]
should be fixed with #8, please review and merge.

**Comment by RobertHa** [comment]
Sorry, nicht während ich ohne Laptop hier bin und nur mein handy habe. Frag
mich gern spezifisch fragen, aber Reviews klappen nicht recht.
